// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVholvRo5FrA5zio_2nYKQFH9u8iWZBvw',
    appId: '1:467913943771:web:89a4dc3464d33cd598bafe',
    messagingSenderId: '467913943771',
    projectId: 'twitter2-a6809',
    authDomain: 'twitter2-a6809.firebaseapp.com',
    storageBucket: 'twitter2-a6809.appspot.com',
    measurementId: 'G-3DFVV018XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2K_sHLjqTDGS8CcJ7Id5ha4kVMVi8MI',
    appId: '1:467913943771:android:b328a891dfdae0e698bafe',
    messagingSenderId: '467913943771',
    projectId: 'twitter2-a6809',
    storageBucket: 'twitter2-a6809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdoiXhjJ15cBOtcqKMyTigXsFRLc4Bmo',
    appId: '1:467913943771:ios:73713441e19a68b798bafe',
    messagingSenderId: '467913943771',
    projectId: 'twitter2-a6809',
    storageBucket: 'twitter2-a6809.appspot.com',
    iosBundleId: 'com.example.twitter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwdoiXhjJ15cBOtcqKMyTigXsFRLc4Bmo',
    appId: '1:467913943771:ios:73713441e19a68b798bafe',
    messagingSenderId: '467913943771',
    projectId: 'twitter2-a6809',
    storageBucket: 'twitter2-a6809.appspot.com',
    iosBundleId: 'com.example.twitter2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVholvRo5FrA5zio_2nYKQFH9u8iWZBvw',
    appId: '1:467913943771:web:f00745cb2e0e8e0098bafe',
    messagingSenderId: '467913943771',
    projectId: 'twitter2-a6809',
    authDomain: 'twitter2-a6809.firebaseapp.com',
    storageBucket: 'twitter2-a6809.appspot.com',
    measurementId: 'G-G1YLCPNB4H',
  );
}
